Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  
Lint/EmptyClass:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/SwapValues:
  Enabled: true

# ハッシュの指摘を無視する
Style/HashSyntax:
  Enabled: false

# ""の指摘を無視する
Style/StringLiterals:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 文字列リテラルの指摘を無視する
Style/FrozenStringLiteralComment:
  Enabled: false

# 一貫性のないインデントを無視する
Layout/IndentationConsistency:
  Enabled: false

# ブロックの行の上限を無視する
Metrics/BlockLength:
  Enabled: false

# メソッド名の上行を無視する
Metrics/MethodLength:
  Enabled: false

# クラスドキュメントコメントを無視する
Style/Documentation:
  Enabled: false

# 文字列の長さの上限を無視する
Layout/LineLength:
  Enabled: false

# 空メソッドを一行に変換するのを無視する
Style/EmptyMethod:
  Enabled: false

# 配列の前に%i,%Iをつける制限を無視する
Style/SymbolArray:
  Enabled: false

# 変数名のgetを許容する
Naming/AccessorMethodName:
  Enabled: false

# 修飾子を優先する
Style/IfUnlessModifier:
  Enabled: false

# ネストされたモジュール定義を使用する
Style/ClassAndModuleChildren:
  Enabled: false

# ガード句に変換しない
Style/GuardClause:
  Enabled: false

# 分岐条件のサイズ
Metrics/AbcSize:
  Enabled: false

# ブロックコメントを許可
Style/BlockComments:
  Enabled: false

# warnで無効にしない
Style/StderrPuts:
  Enabled: false

# 高すぎる複雑度を許可する
Metrics/CyclomaticComplexity:
  Enabled: false

# PROGRAM_NAMEを優先しない
Style/SpecialGlobalVars:
  Enabled: false

# 高すぎる複雑さを許可する
Metrics/PerceivedComplexity:
  Enabled: false

# 三項演算子を許可する
Style/MultilineTernaryOperator:
  Enabled: false

# %wを使用しない
Style/WordArray:
  Enabled: false

# 代わりにprocを使用しない
Style/Proc:
  Enabled: false

# 変数名を変えない
Style/GlobalStdStream:
  Enabled: false

# localhost:3000を利用する
Style/IdenticalConditionalBranches:
  Enabled: false

# || を利用しない
Style/RedundantCondition:
  Enabled: false

# 重複を許可する
Lint/DuplicateMethods:
  Enabled: false

# 引数名を許可する
Lint/UnusedBlockArgument:
  Enabled: false

# テキストを許可する
Style/SymbolProc:
  Enabled: false

# 文字列連結を許可する
Style/StringConcatenation:
  Enabled: false

# __dir__書き換えを無効にする
Style/ExpandPathArguments:
  Enabled: false